### ISSUE TITLE
System.Interactive

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#1]
Reference System.Interactive and remove duplicate methods

**Comment by viceroypenguin** [comment]
I thought about that, but I did not realize that System.Interactive even existed, and I've relied on MoreLINQ for all of my extra methods for forever. For me, adding System.Interactive would import the full package at once without having to remember System.Interactive as a separate reference. Thoughts?

**Comment by Arithmomaniac** [comment]
If someone is migrating from MoreLinq, they already need to read migration instructions, right? Just put it in there.

Also, you want the package **System.Interactive.Async**.

**Comment by viceroypenguin** [comment]
**[System.Interactive](https://www.nuget.org/packages/System.Interactive/)** is the non-async version. **[System.Interactive.Async](https://www.nuget.org/packages/System.Interactive.Async/)** is the async version.

That's a good point. That said, I think some of the existing APIs rely on functions that are implemented in System.Interactive, so it'd be better to reference that than duplicate the code anyway. I'll look at that when I start removing functions.

**Comment by viceroypenguin** [comment]
Similarly, there are some methods that get renamed. For example, MoreLINQ calls it `.Batch()`, but System.Interactive calls it `.Buffer()`. I'll probably keep `.Batch()` as a forward to `.Buffer()` for convenience sake.

**Comment by viceroypenguin** [comment]
Query: I'm looking at the code in System.Interactive, and noticing that a lot of it has not been touched since 2018. Wondering if it makes sense to actually rely on it or to keep what we've got and copy whatever methods we're missing that they have?

**Comment by Arithmomaniac** [comment]
The project is owned by the dotnet organization itself and has consistently seen updates. I'd rely on it until it's been proven you can't. (They were pretty quick to handle .NET 6 incompatibilities, for example.)

**Comment by viceroypenguin** [comment]
@Arithmomaniac - point for discussion: The implementation `.Scan()` is incorrect in System.Interactive, and they do not appear interested in correcting it. Thoughts?

**Comment by Arithmomaniac** [comment]
Weird. Guess this at least partially refutes https://github.com/viceroypenguin/SuperLinq/issues/1#issuecomment-1153816623.

Given SI's widespread use, I'd still defer to its implementation and rename `Scan` in this library to e.g. `ScanWithFirst` and mark it as a breaking change in SuperLinq.
