### ISSUE TITLE
Add `List<T>` item finding methods

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#109]
`List<T>` has some useful finding methods that should be implemented for `IEnumerable<T>`

* [x] `IndexOf<T>(this IEnumerable<T> source, T value[, Index index])`
* [x] `LastIndex<T>(this IEnumerable<T> source, T value[, Index index])`
* [x] `FindIndex<T>(this IEnumerable<T> source, [Index index,] Func<T, bool> predicate)`
* [x] `FindLastIndex<T>(this IEnumerable<T> source, [Index index,] Func<T, bool> predicate)`
* [x] Update `(Last)IndexOf` to proxy to `Find(Last)Index`

**Comment by Arithmomaniac** [comment]
Will these use the existing `List<T>` ones where applicable? I'm not great on overload disambiguation

**Comment by viceroypenguin** [comment]
Yes. Overload rules state that if two methods have the same signature, then the one provided by the class will be used instead of the extension method.

**Comment by Arithmomaniac** [comment]
Could `(Last)`IndexOf` be implemented as calls to `Find(Last)Index`?

**Comment by viceroypenguin** [comment]
Hmmm... possibly? Would add a closure to the `(Last)IndexOf` methods for the `predicate` parameter, but that should be fine for what we're doing, I think. I'm going to get `FindLastIndex` into the codebase, and then I might convert `(Last)IndexOf`...

**Comment by Arithmomaniac** [comment]
After that, it might be more worthwhile to add `I(ReadOnly)List` optimizations when it's only half the work 😉 
(Note that dotnet themselves only optimize for `IList`; see https://github.com/dotnet/runtime/issues/42254#issuecomment-1012981622)

**Comment by viceroypenguin** [comment]
Ok, `FindLastIndex` is in.  

I think on consideration, I'll defer to maintainability for this one; this means no `IList<>` version of `FindLastIndex` or `LastIndexOf` (even though in some/many cases, it may improve performance). 

But that does mean I'll update the `(Last)IndexOf` operators to proxy to `Find(Last)Index`.
