### ISSUE TITLE
Replace T4 code generation with a C# source generator

### ISSUE THREAD

**Issue by Arithmomaniac** [viceroypenguin/SuperLinq#11]
https://github.com/morelinq/MoreLINQ/discussions/799

**Comment by viceroypenguin** [comment]
There was a valid concern in the old library, but it has since been addressed. a) he was concerned about extensions.g.cs, which we're no longer using; b) c#10 source generators are friendlier to static source generation, which should help.

**Comment by viceroypenguin** [comment]
Fixed w/ 1e69be7
