### ISSUE TITLE
Improve Join functions

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#19]
* [ ] ~~Add .LoopJoin() [Inner, Left outer, Cross Apply, Outer Apply]~~ This is just .Select()/.SelectMany()
* [ ] ~~Add .HashJoin() [Inner, Left outer, Right outer, Full outer]~~ .Join()/.GroupJoin() uses hash join - just need to clean up .LeftJoin()/.RightJoin(); maybe improve .FullJoin()
* [ ] Add .MergeJoin() [Inner, Left outer, Right outer, Full outer]
* [ ] Update existing methods (.FullJoin(), OrderedMerge(), etc.) as implementations of above

Debate: Add .LoopJoin() and .HashJoin() as aliases to .Select() and .Join(), for completeness/equivalence to .MergeJoin()?

**Comment by Arithmomaniac** [comment]
I wouldn't add aliases for completeness, it just increases the surface you need to worry about re compatibility with other libraries and compatibility with other functions you may want to write instead in the future.

**Comment by viceroypenguin** [comment]
I feel like the surface is already wonky due to the current implementations of `.LeftJoin()`, `.FullJoin()`, and `.OrderedMerge()`.

If I were to design from scratch, I'd follow sql server design and terminology and say that there are three join types (loop, hash, and merge) and four join operations (inner, left outer, right outer, full outer), for a total of ten potential joins (loop cannot do right outer or full outer). 

As such, I would do one of the following:
1. ```csharp
   public IEnumerable<TResult> Join<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinType joinType, JoinOperation joinOperation, ...); 
   ```

1. ```csharp
   public IEnumerable<TResult> InnerJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinType joinType, ...); 
   public IEnumerable<TResult> LeftOuterJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinType joinType, ...); 
   public IEnumerable<TResult> RightOuterJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinType joinType, ...); 
   public IEnumerable<TResult> FullOuterJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinType joinType, ...); 
   ```

1. ```csharp
   public IEnumerable<TResult> LoopJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinOperation joinOperation, ...); 
   public IEnumerable<TResult> HashJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinOperation joinOperation, ...); 
   public IEnumerable<TResult> MergeJoin<TLeft, TRight, TKey, TResult>(this IEnumerable<TLeft> left, IEnumerable<TRight> right, JoinOperation joinOperation, ...); 
   ```

(NB: Options 2/3 could be implemented as simple calls into Option 1).

The questions that should be answered:
1. Which option (if any) of the above should be implemented? If none, then simply implement `.MergeJoin()` and leave the existing `.LeftJoin()`, `.RightJoin()`, `.FullJoin()`, `.OrderedMerge()` alone?
   * My preference would be 2 with a default `JoinType` of `Adaptive` (see 3 below). The other advantage of option 2 is that some parameters can be elided when not used, which is not available with option 3. Option 1 might be available since it's the core of the implementation of anyway?
   * Counter-point: `.MergeJoin()` will recommend an additional parameter indicating whether the underlying data is already sorted. Maybe we rely on `left is IOrderedEnumerable<>` or something, but that doesn't tell us whether the underlying data is sorted according to our expectations. There would be a (possibly marginal?) performance gain in trusting the user that the data is already sorted instead of always sorting it. However, options 1/2 do not allow for the consumer informing us that it is already sorted.
2. Should the existing methods be `Obsolete` or not?
   * I'd be inclined to do so, especially since low number of users for SuperLinq so far. However, they may be actively used by consumers of MoreLINQ, and it would be an additional change on moving. Am not recommending removal, however - existing methods have been around for too long to recommend removal.
3. Further improvement (that could affect opinions on above): add a new `JoinType` of `Adaptive` that would use thresholds to decide between `Loop`, `Hash`, or `Merge` join. 
   * Using `Adaptive` would allow users to generally not care about the join type, only the operation. Consumers who have more information about their data can prefer a specific join type.

**Comment by Arithmomaniac** [comment]
1. Version 2 is more in accordance with the original spirit of LINQ, which is to extend C# with SQL-like functional syntax. T-SQL corresponds with 2), not 3). It's also much closer to the original MoreLINQ syntax.
2. Yes obsolete them; you'll want to remove them eventually, especially if you go with option 2) (where they are largely just renamed).
3. Could be very complex, no? Should be broken out.

**Comment by viceroypenguin** [comment]
Thank you for your thoughts. Agreed - in SQL one usually specifies the logical operation while allowing the server to determine the physical operation. Only in rare high-performance bad-optimization cases would one directly specify the physical operation. 

And yes, `Adaptive` would be a separate task down the road. Will require some research to determine thresholds for switching join types.

However, as I start implementation, I'm realizing an issue with what I've written. `Hash` type joins require an `IEqualityComparer<TKey>` (specifically _both_ `.Equals()` and `.GetHashCode()`) in order to bucket and look up keys. On the other hand, `Merge` type joins require an `IComparer<TKey>` in order to sort the inputs and iterate properly through both inputs. `Loop` type joins can use either, because it only cares about equality.

When `TKey` is a natural type (`int`, `float`, `string`) without a custom comparer, then it's super easy, because we can just use the default equality and value comparers in each join type without issue. But when we want to use custom comparer, especially for non-natural key types, then it creates issues.

Options:
1. Add both `IEqualityComparer<TKey>?` and `IComparer<TKey>?` parameters. If the relevant comparer for the specified join type is not provided, then that's on the consumer for not providing it.
   ```csharp
   private static IEnumerable<TResult> Join<TLeft, TRight, TKey, TResult>(
   	IEnumerable<TLeft> left,
   	IEnumerable<TRight> right,
   	JoinType joinType,
   	JoinOperation joinOperation,
   	Func<TLeft, TKey> leftKeySelector,
   	Func<TRight, TKey> rightKeySelector,
   	Func<TLeft, TResult>? leftResultSelector,
   	Func<TRight, TResult>? rightResultSelector,
   	Func<TLeft, TRight, TResult> bothResultSelector,
   	IComparer<TKey>? comparer,
   	IEqualityComparer<TKey>? equalityComparer)
   { }
   ```

2. Implement each join type twice: once with `TKey` constraint for both `IEquatable<TKey>` and `IComparable<TKey>`, and again with `string` allowing `StringComparer` parameter (which implements both.
   ```csharp
   private static IEnumerable<TResult> Join<TLeft, TRight, TKey, TResult>(
   	IEnumerable<TLeft> left,
   	IEnumerable<TRight> right,
   	JoinType joinType,
   	JoinOperation joinOperation,
   	Func<TLeft, TKey> leftKeySelector,
   	Func<TRight, TKey> rightKeySelector,
   	Func<TLeft, TResult>? leftResultSelector,
   	Func<TRight, TResult>? rightResultSelector,
   	Func<TLeft, TRight, TResult> bothResultSelector)
   	where TKey : IComparable<TKey>, IEquatable<TKey>
   { }
   
   private static IEnumerable<TResult> Join<TLeft, TRight, TResult>(
   	IEnumerable<TLeft> left,
   	IEnumerable<TRight> right,
   	JoinType joinType,
   	JoinOperation joinOperation,
   	Func<TLeft, string> leftKeySelector,
   	Func<TRight, string> rightKeySelector,
   	Func<TLeft, TResult>? leftResultSelector,
   	Func<TRight, TResult>? rightResultSelector,
   	Func<TLeft, TRight, TResult> bothResultSelector,
   	StringComparer comparer)
   { }
   ```

3. Go back to option 3 above; this would allow asking for the specific type of comparer for the join type. Option 3 is actually the base implementation, since this is where the real code sits, with filters for whether to return certain values based on the logical join operation. Options 1/2 sit on top of Option 3 regardless. 

I can see good arguments for all three options here, but I'm inclined to go with either options 2 or 3. Option 2 would cover 95%+ of the potential key cases - it's not often people will need a custom comparer that wouldn't be covered by improving the key selection. Option 3 would be more explicit in the requirements, even if it isn't as LINQ-y as other solutions.

**Comment by viceroypenguin** [comment]
Found a solution that doesn't require limiting `TKey` and `string`:

```csharp
private static IEnumerable<TResult> Join<TLeft, TRight, TKey, TResult>(
	IEnumerable<TLeft> left,
	IEnumerable<TRight> right,
	JoinType joinType,
	JoinOperation joinOperation,
	Func<TLeft, TKey> leftKeySelector,
	Func<TRight, TKey> rightKeySelector,
	Func<TLeft, TResult>? leftResultSelector,
	Func<TRight, TResult>? rightResultSelector,
	Func<TLeft, TRight, TResult> bothResultSelector)
{ }

private static IEnumerable<TResult> Join<TLeft, TRight, TKey, TResult>(
	IEnumerable<TLeft> left,
	IEnumerable<TRight> right,
	JoinType joinType,
	JoinOperation joinOperation,
	Func<TLeft, TKey> leftKeySelector,
	Func<TRight, TKey> rightKeySelector,
	Func<TLeft, TResult>? leftResultSelector,
	Func<TRight, TResult>? rightResultSelector,
	Func<TLeft, TRight, TResult> bothResultSelector)
{ }
```
