### ISSUE TITLE
Equivalent support for IAsyncEnumerable

### ISSUE THREAD

**Issue by Arithmomaniac** [viceroypenguin/SuperLinq#2]
For each current method, add an equivalent method for `IAsyncEnumerable`s.

Progress:
- [ ] ~~Acquire~~
- [ ] ~~Aggregate~~
- [x] AggregateRight
- [x] AtLeast
- [x] AtMost
- [x] Backsert
- [ ] ~~Batch~~
- [ ] ~~Cartesian~~
- [x] Choose
- [x] CompareCount
- [x] Consume
- [x] CountBetween
- [x] CountBy
- [x] CountDown
- [x] DenseRank
- [x] DenseRankBy
- [x] DistinctBy
- [x] ElementAt (pre-.NET 6)
- [x] EndsWith
- [x] Exactly
- [x] ExceptBy
- [ ] Exclude (#10)
- [x] FallbackIfEmpty
- [x] FillBackward
- [x] FillForward
- [ ] ~~Flatten~~
- [x] Fold
- [x] From
- [ ] FullGroupJoin (#19)
- [ ] FullJoin (#19)
- [x] Generate
- [x] GenerateByIndex
- [x] GroupAdjacent
- [x] Index
- [x] IndexBy
- [x] Insert
- [x] Interleave
- [x] Lag
- [x] Lead
- [ ] LeftJoin (#19)
- [ ] Move (#27)
- [x] OrderBy
- [ ] OrderedMerge (#19)
- [x] Pad
- [x] PadStart
- [x] PartialSort
- [x] PartialSortBy
- [x] Partition
- [ ] Permutations (#20)
- [ ] ~~Pipe~~
- [x] PreScan
- [x] Random
- [x] RandomDouble
- [ ] RandomSubset (#20)
- [x] Rank (#13)
- [x] RankBy (#13)
- [ ] ~~Return~~
- [ ] RightJoin (#19)
- [x] RunLengthEncode
- [x] ScanBy
- [x] ScanRight
- [x] Segment
- [x] Sequence
- [ ] Shuffle (#20)
- [x] SkipUntil
- [ ] ~~Slice~~
- [x] SortedMerge
- [x] Split
- [x] StartsWith
- [ ] Subsets (#20)
- [x] TagFirstLast
- [x] Take (pre-.NET 6)
- [x] TakeEvery
- [x] TakeUntil
- [x] ThenBy
- [ ] ~~ToArrayByIndex~~
- [ ] ~~ToDataTable~~
- [ ] ~~ToDelimitedString~~
- [ ] ~~ToDictionary~~
- [ ] ~~ToLookup~~
- [ ] ~~Transpose~~
- [ ] TraverseBreadthFirst (#21)
- [ ] TraverseDepthFirst (#21)
- [ ] ~~Trace~~
- [x] TrySingle
- [ ] ~~Unfold~~
- [x] Window
- [x] WindowLeft
- [x] WindowRight
- [x] ZipLongest
- [x] ZipShortest

**Comment by viceroypenguin** [comment]
Released preview of [`SuperLinq.Async`](https://www.nuget.org/packages/SuperLinq.Async).  Nowhere near equivalent yet, but architecture is in place and methods can start moving over.

**Comment by viceroypenguin** [comment]
@Arithmomaniac - You mind taking a look through the latest version of the code and validating? I don't have all of the functions migrated, but I've identified separate issues for the remaining ones. I think the latest upload should be good for prod release of v4.

**Comment by viceroypenguin** [comment]
Thanks for the review! I'll definitely update the readme - good advice!

**Comment by viceroypenguin** [comment]
Done. I think I'll release 4.0.0 tomorrow unless you have any other objections.
