### ISSUE TITLE
`WhereLead` and `WhereLag` operators

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#303]
`Lead` and `Lag` operators are useful, but there are times when you only want to filter based on the next or previous value, but do not need the combined value after filtering. This would be a shortcut for `source.Lead(...).Where(...).Select(x => x.current)`.

**Comment by tacosontitan** [comment]
Do you have a vision for this implementation and an example of the problem it's trying to overcome? I'd be more than glad to assist with it given some additional clarity!

**Comment by viceroypenguin** [comment]
> Do you have a vision for this implementation and an example of the problem it's trying to overcome? I'd be more than glad to assist with it given some additional clarity!

Sure!

So technically, the behavior already exists in SuperLinq, but it's awkward and unwieldy, which is why I'm suggesting additional operators for these.

The existing behavior would be as such:
```cs
var source = Enumerable.Range(0, 30).Select(x => DateTime.Today.AddDays(x));

var result = source
  .Lead(1)
  .Where(x => x.current.Month != x.lead.Month)
  .Select(x => x.current);
```

This would return a list of the last day of the month. I recognize that there are many easier ways to _get the last day of the month_, but the point is to highlight a potential use-case for `.Lead().Where().Select()`, if this code were generalized to an input sequence trying to identify certain conditions.

The simpler solution would look like:
```cs
var result = source.WhereLead(1, x => x.current.Month != x.lead.Month);
```

where `result` is still an `IEnumerable<TSource>`. 

For how to implement, you should be able to take notes from the `Lead` and `Lag` operators, though due to the uncertain lengths, the `ListIterator` optimizations here will not be viable for `WhereLead` and `WhereLag`.

**Comment by tacosontitan** [comment]
Thanks for the swift reply! Given the example, `WhereLead` reads a bit clunky to me at the moment based on the existing behavior. Is there a reason to prefer `WhereLead` over the inverse of `LeadWhere`? For example:

```csharp
var result = source.LeadWhere(1, x => x.current.Month != x.lead.Month);
```

**Comment by viceroypenguin** [comment]
I'm open to argument, but my perspective is that `WhereLead` is a more accurate title for the operator. The goal of the operator is to filter, so it is a `Where` operator; the `Lead`/`Lag` is the mechanism. To me, `LeadWhere` indicates that the `Lead` is the goal and the `Where` is the mechanism.  Thoughts?

**Comment by tacosontitan** [comment]
That makes more sense to me now, thank you for the clarity!
