### ISSUE TITLE
Add per-element version of `Timeout` async operator

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#350]

**Comment by julienasp** [comment]
i'll work on this one this week!

**Comment by julienasp** [comment]
Hi, what aspect of the per-element you want to bring ?

like a non-breaking? per element? 

because with the current implementation we do have a set timeout per async enumerator iteration

i ran that 
```[Fact]
	public async Task TimeoutNoException()
	{
		await using var ts = AsyncEnumerable.Range(1, 5)
			.SelectAwaitWithCancellation(async (x, ct) =>
			{
				await Task.Delay(TimeSpan.FromSeconds(59), ct); // 59 secondes 
				return x;
			})
			.AsTestingSequence();

		var result = ts.Timeout(TimeSpan.FromMinutes(1)); // 60 secondes 

		await result.AssertSequenceEqual(1, 2, 3, 4, 5);
	}`

**Comment by viceroypenguin** [comment]
I was thinking of an overload like this:
```cs
public IAsyncEnumerable<T> Timeout(this IAsyncEnumerable<T> source, Func<T, TimeSpan> timeoutFunc);
```

Where the timeout value is selected per-element.

**Comment by julienasp** [comment]
> I was thinking of an overload like this:
> 
> ```cs
> public IAsyncEnumerable<T> Timeout(this IAsyncEnumerable<T> source, Func<T, TimeSpan> timeoutFunc);
> ```
> 
> Where the timeout value is selected per-element.

```
public async Task TimeoutNoException()
	{
		await using var ts = AsyncEnumerable.Range(1, 5)
			.SelectAwaitWithCancellation(async (x, ct) =>
			{
				await Task.Delay(TimeSpan.FromSeconds(59), ct); // 59 secondes 
				return x;
			})
			.AsTestingSequence();

		var result = ts.Timeout(x => x % 0 ?  TimeSpan.FromMinutes(1) : TimeSpan.FromMinutes(2)); 

		await result.AssertSequenceEqual(1, 2, 3, 4, 5);
}
```
	
	
To enable something like that?

Considering that the func would need a completed Task<T> to be able to run. 

Like 

```
var moveNextTask = moveNextVt.AsTask();
var timeoutvalue = timeoutFunc(moveNextVt.Result); // blocking operation, without a timeout in it
var delayTask = Task.Delay(timeoutvalue, cancellationToken);
var successTask = await Task.WhenAny(moveNextTask, delayTask).ConfigureAwait(false);

if (successTask == delayTask)
{
  cts.Cancel();
  _ = await moveNextTask.ConfigureAwait(false);
  throw new TimeoutException("The operation has timed out.");
}

Im sorry for all the dumm questions, im really trying to make sure that i code the right thing

**Comment by viceroypenguin** [comment]
> Im sorry for all the dumm questions, im really trying to make sure that i code the right thing

All good. 

Take a look at the existing `Timeout` implementation - most likely all that you would need is to move the `Core` to the new overload with some dynamic evaluation to get the `timeout` value, and the existing overload would change to a simple `return Timeout(source, _ => timeout);`.

**Comment by julienasp** [comment]
I'm seriously unable to understand what you are envisioning for that feature.

As soon as we create a new overload, we will still have the same issue, I mentionned earlier

we have a source, we have a func to retrieve a Timeout value.

But that func needs **the T element to figure out the timeout** value. So we need to await that ValueTask

via 
- await e.MoveNextAsync(), then use **timeoutFunc(e.Current)**

But in doing so, the timeout is now useless (we already waited, and maybe exceed that timeout), unless we use that current T func to place a timeout for the Next element in line.

or 

We start a Stopwatch and mesure from the start to the e.Current availablitity and if that bust the funcTimeout(e.Current) then we throw.

I'm very confused

**Comment by viceroypenguin** [comment]
Oh! Good catch. I hadn't thought that through. Thanks for realizing this. Closing this issue.

**Comment by julienasp** [comment]
> Oh! Good catch. I hadn't thought that through. Thanks for realizing this. Closing this issue.

No problem! I'm just glad that I wasn't asking question for nothing :) 

I also added 2 tests for the timeout feature, there's a pending PR. There was a case that was not covered by the tests but that you already planned for in the current implementation

https://github.com/viceroypenguin/SuperLinq/pull/463
