### ISSUE TITLE
Revert `CountBy` return type to `KeyValuePair<,>`

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#490]
Per https://github.com/dotnet/runtime/issues/77716#issuecomment-1664448577, the approved API for `CountBy` returns `IEnumerable<KeyValuePair<int, TSource>>` instead of `IEnumerable<(int, TSource)>`. SuperLinq should revert the return type to match the corelib approved API to encourage code-compatibility between SuperLinq and corelib.

**Comment by a-reny** [comment]
Can I take a go at this?

**Comment by viceroypenguin** [comment]
Sure! Feel free to ask if you have any questions.
