### ISSUE TITLE
Simplify `RandomSubsetImpl` code

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#540]
Currently, `RandomSubsetImpl` receives a `Func<IEnumerable<T>, (T[], int)>` parameter. However, both callers use `s.ToArray()` for the array value and one uses `array.Length` as the int value. It would be better to move the `.ToArray()` call inside `RandomSubsetImpl`, and add an `int?` parameter that can be used to evaluate the subset length (if `null`, then set to `array.Length`).

**Comment by kthurman59** [comment]
I may have an answer for this, would you assign this?  Or what process works best for you?  I am adaptable!

**Comment by viceroypenguin** [comment]
Assigned! Thanks.

Please note that I have updated the codebase to C#12, so you will need to do development with the preview sdk until net8 is released on 14-Nov.

**Comment by kthurman59** [comment]
Shouldn't be a problem!

**Comment by kthurman59** [comment]
Quick update, still working on this.
