### ISSUE TITLE
Add `Rank`/`DenseRank` overloads

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#544]
Currently, `Rank(By)` and `DenseRank(By)` do not have overloads that accept a sort direction. This means the consumer must provide a reverse comparer in order to rank in descending order. We should provide overloads that will allow the consumer to provide an `OrderBy` value expressing the sort order of items to be ranked.

**Comment by Head0nF1re** [comment]
Hey @viceroypenguin, I will start working on this one tomorrow
