### ISSUE TITLE
Add ZipMany

### ISSUE THREAD

**Issue by thinker227** [viceroypenguin/SuperLinq#600]
Add a `ZipMany` (alternatively `ZipAll`) method which acts like regular `Zip` but on an arbitrary amount of enumerables.
```cs
public static IEnumerable<IEnumerable<T>> ZipMany<T>(this IEnumerable<IEnumerable<T>> source);
```
Depending on the implementation, the return could instead be `IEnumerable<IList<T>>`.

**Comment by viceroypenguin** [comment]
NB: Semantics should be similar to `Zip()`/`ZipShortest()`.

**Comment by viceroypenguin** [comment]
Upon further review, this already exists, under the name `Transpose()`. Please review and let me know if it does not cover the needs here.
