### ISSUE TITLE
Reduce visual noise with primary constructors

### ISSUE THREAD

**Issue by Head0nF1re** [viceroypenguin/SuperLinq#611]
Primary constructors were introduced in C# 12, we should consider replacing the normal flow of adding a ctor in order to initialize fields. This would reduce some visual noise, just need to be aware of [double capturing](https://blog.jetbrains.com/dotnet/2023/11/23/primary-constructors-using-csharp-12-in-rider-and-resharper/#double-capture-warnings).

With primary constructors, AKA parameters for classes, we would be able to do: 

this

```csharp
private sealed class ExcludeCollectionIterator<T>(
	ICollection<T> source,
	int startIndex,
	int count) : CollectionIterator<T>
{
	public override int Count =>
		source.Count < startIndex ? source.Count :
		source.Count < startIndex + count ? startIndex :
		source.Count - count;

	protected override IEnumerable<T> GetEnumerable() =>
		ExcludeCore(source, startIndex, count);
}

```

instead of
```csharp
private sealed class ExcludeCollectionIterator<T> : CollectionIterator<T>
{
	private readonly ICollection<T> _source;
	private readonly int _startIndex;
	private readonly int _count;

	public ExcludeCollectionIterator(ICollection<T> source, int startIndex, int count)
	{
		_source = source;
		_startIndex = startIndex;
		_count = count;
	}

	public override int Count =>
		_source.Count < _startIndex ? _source.Count :
		_source.Count < _startIndex + _count ? _startIndex :
		_source.Count - _count;

	protected override IEnumerable<T> GetEnumerable() =>
		ExcludeCore(_source, _startIndex, _count);
}
```
<br/>

The only issue is that primary constructors params can't be `readonly`, the solution would be to choose one option:
1. Initialize a `private readonly` field, still reducing code by removing the ctor.
2. Ignore it.

My purist side says "initialize the readonly fields", while my practical side says to just ignore it. What do you think?

**Comment by viceroypenguin** [comment]
For SuperLinq, I think we can get away with 2. ignoring it. And as far as double-capturing goes, we can just turn some of the compiler warnings for primary constructors into errors. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/constructor-errors#primary-constructor-declaration
