### ISSUE TITLE
`.CopyTo()`

### ISSUE THREAD

**Issue by viceroypenguin** [viceroypenguin/SuperLinq#72]
In order to improve allocations (ex: `ArrayPool.Rent()`) or to copy data to a specific pre-existing place, it may be useful to copy a sequence. Following APIs to be implemented:

```csharp
void CopyTo<T>(this IEnumerable<T> source, Span<T> span); 
void CopyTo<T>(this IEnumerable<T> source, IList<T> list);
void CopyTo<T>(this IEnumerable<T> source, IList<T> list, Index index);
```

Semantics:
* `void CopyTo<T>(this IEnumerable<T> source, IList<T> list);` will throw an exception if the `source` is longer than `array`. If `source` is shorter than `array`, then the remainder of `array` will be untouched.

**Comment by Arithmomaniac** [comment]
- I think `IList<T>` covers all three cases, and you can just do type checking to resolve behavior.
- We should optimize for sources of type `(ReadOnly)Span`, and targets of type `Span`.

**Comment by viceroypenguin** [comment]
Yeah, `(ReadOnly)Span` should be on there. Thanks for pointing that out. 

Consolidating to `IList` and then dispatching out reduces performance slightly, due to the type check in the other side. Better to have the three separated, especially since the code will be different between the three (direct assignment vs addrange vs foreach/add).

**Comment by viceroypenguin** [comment]
And yeah, optimizing for input type will be useful. Thanks for pointing that out.

**Comment by Arithmomaniac** [comment]
Just realized, I would expect `CopyTo` to only overwrite where it matches the `IEnumerable`, not to wipe the whole thing. (How `Array.CopyTo`, `Span.CopyTo` works IIRC).

**Comment by Arithmomaniac** [comment]
> Consolidating to `IList` and then dispatching out reduces performance slightly, due to the type check in the other side. Better to have the three separated, especially since the code will be different between the three (direct assignment vs addrange vs foreach/add).

This isn't how LINQ works generally; it favors surface simplicity over super high performance. (Hence internal abstractions like `IIListProvider<T>`.)

**Comment by viceroypenguin** [comment]
> This isn't how LINQ works generally; it favors surface simplicity over super high performance. (Hence internal abstractions like `IIListProvider<T>`.)

Touché.
