### ISSUE TITLE
`.WithIndex()` to easily get an index in `foreach`

### ISSUE THREAD

**Issue by jibbers42** [viceroypenguin/SuperLinq#79]
Credit to https://thomaslevesque.com/2019/11/18/using-foreach-with-index-in-c/

It's a small convenience, but I thought I'd suggest adding `.WithIndex()` to this lib in case you like it.

```c#
using System.Linq;
...

public static IEnumerable<(T item, int index)> WithIndex<T>(this IEnumerable<T> source)
{
    return source.Select((item, index) => (item, index));
}
```

```c#
foreach (var (item, index) in collection.WithIndex())
{
    DoSomething(item, index);
}
```

**Comment by viceroypenguin** [comment]
It's already there, under the name `Index()`. See here: https://github.com/viceroypenguin/SuperLinq/blob/master/Source/SuperLinq/Index.cs.

Hope this helps!

**Comment by jibbers42** [comment]
Ha, sorry, not sure how I missed that!

**Comment by viceroypenguin** [comment]
No worries. I miss stuff all the time. Have a good one! :)
