### ISSUE TITLE
Mark Batch as obsolete due to Chunk

### ISSUE THREAD

**Issue by Arithmomaniac** [viceroypenguin/SuperLinq#8]
https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.chunk?view=net-6.0

**Comment by viceroypenguin** [comment]
I have Batch forwarded to `.Buffer()` in older fx, and `.Chunk()` in .net6. I'm not going to Obsolete it though, for those who want a common API; also for easier migration from MoreLINQ. Thoughts?
